### ISSUE TITLE
请问是否可以直接在开源项目中使用?

### ISSUE THREAD

**Issue by MummyDing** [NashLegend/SwipetoFinishActivity#2]
你好,我现在在做的一个开源项目想用到这种效果,不知是否可以直接使用你的代码?

**Comment by MummyDing** [comment]
这是我准备应用的项目:
https://github.com/MummyDing/Leisure
https://github.com/MummyDing/Awesome-Campus

**Comment by NashLegend** [comment]
可以 随便用

**Comment by MummyDing** [comment]
@NashLegend  好的,谢谢. 刚刚也大概看了下代码,过段时间自己再写下试试.
