### ISSUE TITLE
键盘在显示与影藏过程中能看到桌面

### ISSUE THREAD

**Issue by kkroid** [NashLegend/SwipetoFinishActivity#3]
键盘在显示与影藏过程中， 由于整个App的background是透明的，所以可以可以在那一瞬间看到桌面

**Comment by NashLegend** [comment]
难道是最底部的Activity设置了透明？最底部的设置透明后不同的手机上可能会有不同的奇怪的bug

**Comment by kkroid** [comment]
@NashLegend 最底部不是透明的    但是就看到了最底部的这个activity    反正最下面是什么就会看到什么，我估计是因为键盘弹出来那一瞬间，页面被顶上去，就看到了下面的acitivity
